name: Fetch SVG and Push

on:
  schedule: # execute every 24 hours
    - cron: "0 0 */3 * *"
  workflow_dispatch:

jobs:
  fetch_and_push_svg:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5.0.1

    - name: recreate SVG directory
      run: |
        rm -rf svg
        mkdir -p svg

    - name: Fetch SVG content
      run: |
        # GitHub Readme Stats
        curl -H 'Cache-Control: no-cache' -o svg/image.svg "https://github-readme-status-clone-01.vercel.app/api?username=matuyuhi&show=reviews,prs_merged,prs_merged_percentage&hide=stars&show_icons=true&title_color=fff&icon_color=79ff97&text_color=9f9f9f&bg_color=151515&include_all_commits=true"

        # GitHub Profile Trophy
        # curl -H 'Cache-Control: no-cache' -o svg/trophy.svg "https://github-profile-trophy-kannan.vercel.app?username=Matuyuhi&count_private=true&no-frame=true&column=5&rank=-B"
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Clone trophy generator
      run: |
        git clone https://github.com/Erik-Donath/github-profile-trophy.git .trophy-gen
        git -C .trophy-gen checkout eb0893b31de06841663555d10aa43eb7cf27952f

    - name: Generate trophy SVG
      env:
        GITHUB_TOKEN1: ${{ secrets.SUMMARY_CARDS_TOKEN }}
      run: |
        deno run --allow-net --allow-env --allow-read --allow-write \
          .trophy-gen/render_svg.ts \
          matuyuhi \
          --file svg/trophy.svg \
          --theme classic \
          --no-frame true
          --columns 5 \
          --panel-size 0 \
          --margin-width 10 \
          --margin-height 10
    - name: Commit and Push if changed
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add svg/image.svg svg/trophy.svg
        git diff --staged --quiet || (git commit -m "Add/Update image.svg and trophy.svg from URL" && git push)
