name: GitHub-Profile-Summary-Cards

on:
  schedule: # execute every 24 hours
    - cron: "0 0 */2 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-slim
    name: generate
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@v0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_CARDS_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: "main"
          EXCLUDE: "ShaderLab"
          AUTO_PUSH: true
          
